<a href="https://colab.research.google.com/github/shreecodes11/researchmind/blob/main/researchmind.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q arxiv pandas sentence-transformers faiss-cpu

In [ ]:
import arxiv
import pandas as pd
import numpy as np
import faiss
import torch

from sentence_transformers import SentenceTransformer

In [ ]:
import torch

print("Torch:", torch.__version__)

model = SentenceTransformer("all-MiniLM-L6-v2")

print("Sentence Transformer loaded!")

Torch: 2.11.0+cu128

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Sentence Transformer loaded!

In [ ]:
print(arxiv)

<module 'arxiv' from '/usr/local/lib/python3.12/dist-packages/arxiv/__init__.py'>

In [ ]:
TOPIC = input("Enter Research Topic: ")

print("Topic:", TOPIC)

Enter Research Topic: llm
Topic: llm

In [ ]:
search = arxiv.Search(
    query=TOPIC,
    max_results=20,
    sort_by=arxiv.SortCriterion.Relevance
)

client = arxiv.Client()

print("Search object created successfully!")

Search object created successfully!

In [ ]:
papers = []

for result in client.results(search):

    paper = {
        "Title": result.title,
        "Authors": ", ".join(
            [author.name for author in result.authors]
        ),
        "Published": result.published.date(),
        "Abstract": result.summary,
        "PDF_URL": result.pdf_url
    }

    papers.append(paper)

print("Total Papers Retrieved:", len(papers))

Total Papers Retrieved: 20

In [ ]:
print(papers[0]["Title"])

YouZhi: Towards High-Concurrency Financial LLMs via Adaptive GQA-to-MLA Transition

In [ ]:
df=pd.DataFrame(papers)
df.head()

,Title,Authors,Published,Abstract,PDF_URL
0,YouZhi: Towards High-Concurrency Financial LLM...,"PSBC LLM Team, Huawei LLM Team, Ruihan Long,...",2026-06-04,Large language models (LLMs) drive significant...,https://arxiv.org/pdf/2606.05868v1
1,RETA-LLM: A Retrieval-Augmented Large Language...,"Jiongnan Liu, Jiajie Jin, Zihan Wang, Jiehan C...",2023-06-08,Although Large Language Models (LLMs) have dem...,https://arxiv.org/pdf/2306.05212v1
2,FBI-LLM: Scaling Up Fully Binarized LLMs from ...,"Liqun Ma, Mingjie Sun, Zhiqiang Shen",2024-07-09,This work presents a Fully BInarized Large Lan...,https://arxiv.org/pdf/2407.07093v1
3,Systematic Evaluation of LLM-as-a-Judge in LLM...,"Hui Wei, Shenghua He, Tian Xia, Fei Liu, Andy ...",2024-08-23,LLM-as-a-Judge has been widely applied to eval...,https://arxiv.org/pdf/2408.13006v2
4,Enhancing Jailbreak Attacks on LLMs via Person...,"Zheng Zhang, Peilin Zhao, Deheng Ye, Hao Wang",2025-07-28,Jailbreak attacks aim to exploit large languag...,https://arxiv.org/pdf/2507.22171v3

In [ ]:
print("Rows:",df.shape[0])
print("Columns:",df.shape[1])

Rows: 20
Columns: 5

In [ ]:
for i, title in enumerate(df["Title"]):

    print(f"{i+1}. {title}")

1. YouZhi: Towards High-Concurrency Financial LLMs via Adaptive GQA-to-MLA Transition
2. RETA-LLM: A Retrieval-Augmented Large Language Model Toolkit
3. FBI-LLM: Scaling Up Fully Binarized LLMs from Scratch via Autoregressive Distillation
4. Systematic Evaluation of LLM-as-a-Judge in LLM Alignment Tasks: Explainable Metrics and Diverse Prompt Templates
5. Enhancing Jailbreak Attacks on LLMs via Persona Prompts
6. LLM-42: Enabling Determinism in LLM Inference with Verified Speculation
7. Demystifying AI Platform Design for Distributed Inference of Next-Generation LLM models
8. Can LLMs Lie? Investigation beyond Hallucination
9. Small LLMs Are Weak Tool Learners: A Multi-LLM Agent
10. A Survey of LLM $\times$ DATA
11. Any-Precision LLM: Low-Cost Deployment of Multiple, Different-Sized LLMs
12. Open-LLM-Leaderboard: From Multi-choice to Open-style Questions for LLMs Evaluation, Benchmark, and Arena
13. A Survey on LLM-as-a-Judge
14. RoleRAG: Enhancing LLM Role-Playing via Graph Guided Retrieval
15. Strategist: Self-improvement of LLM Decision Making via Bi-Level Tree Search
16. Harnessing Multiple Large Language Models: A Survey on LLM Ensemble
17. Doing What They Say, Not What They Reason: Locating the Faithfulness Gap in LLM Agents
18. The LLM Bottleneck: Why Open-Source Vision LLMs Struggle with Hierarchical Visual Recognition
19. ODA: Observation-Driven Agent for integrating LLMs and Knowledge Graphs
20. ELIS: Efficient LLM Iterative Scheduling System with Response Length Predictor

In [ ]:
print("TITLE:")
print(df.iloc[0]["Title"])

print("\nAUTHORS:")
print(df.iloc[0]["Authors"])

print("\nABSTRACT:")
print(df.iloc[0]["Abstract"])

TITLE:
YouZhi: Towards High-Concurrency Financial LLMs via Adaptive GQA-to-MLA Transition

AUTHORS:
 PSBC LLM Team,  Huawei LLM Team, Ruihan Long, Junjie Wu, Tianan Zhang, Duo Zhang, Yaozong Wu, Jinbin Fu, Chang Liu, Zhentao Tang, Wenshuang Yang, Xin Wang, Zhihao Song, Ning Huang, Wenjing Xu, Shuai Zong, Shupei Sun, Sen Wang, Jing Hu, Bin Wang, Xinyu Wang, Junkui Ju, Zequn Ding, Jie Ran, Man Luo, Shixiong Kai, Linkai Hou, Kaichao Liang, Hu Zhao, Yang Zhao, Shucheng Lin, Wei Yu, Chenghan Jiang, Jingjing Ding, Jiahui Zhang, Tian Jin, Yuhang Zhang, Dong Guo, Wei Sun, Jun Xie, Jianwei Li, Lei Cao, Pei Li, Jiabin Li, Jia Yuan, Rui Yuan, Jing Zhu, Mingxuan Yuan, Zhangcheng Lv, Xin Jiang, Xiuhong Fei, Xiaozhe Ren, Yulong Li, Zhipeng Zhang, Hang Wang, Zhaohui Xu, Rui Zhao, Yibo He, Xinzhuang Niu

ABSTRACT:
Large language models (LLMs) drive significant financial innovations, yet their high-concurrency deployment is severely bottlenecked by KV cache memory overhead, which inflates infrastructure costs and throttles scalability. To address this, we propose YouZhi-LLM, a highly efficient financial LLM empowered by a comprehensive structural transition and training pipeline natively built on the Huawei Ascend ecosystem. At its algorithmic core, YouZhi-LLM features a layer-adaptive GQA-to-MLA transition framework that dynamically assigns per-layer FreqFold sizes, maximizing KV-cache compression while minimizing perplexity degradation. To recover representation capacity and inject domain expertise, the Ascend-based training pipeline seamlessly integrates generalized knowledge distillation with financial-specific supervised fine-tuning. Evaluations demonstrate the superiority of this systematic approach, with the adaptive transition reducing perplexity degradation by up to 35% over uniform baselines. Crucially, when evaluated on Ascend NPUs via vLLM-Ascend, the massive KV-cache reduction translates directly into deployment efficiency. Compared to their respective base models, YouZhi-7B yields a 12.3% improvement in average financial benchmark score alongside a 2.69$\times$ increase in maximum concurrency; similarly, YouZhi-14B achieves a 7.0% accuracy gain and a 2.43$\times$ concurrency boost, establishing a new paradigm for cost-effective, high-throughput financial inference.

In [ ]:
df.to_csv(
    "retrieved_papers.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!

In [ ]:

from google.colab import files

files.download("retrieved_papers.csv")

In [ ]:
print("Total Papers:", len(df))

print()

print("Oldest Paper:")
print(df["Published"].min())

print()

print("Newest Paper:")
print(df["Published"].max())

Total Papers: 20

Oldest Paper:
2023-06-08

Newest Paper:
2026-06-04

In [ ]:
for i in range(3):

    print(df.iloc[i]["Title"])

    print(df.iloc[i]["PDF_URL"])

    print("-" * 50)

YouZhi: Towards High-Concurrency Financial LLMs via Adaptive GQA-to-MLA Transition
https://arxiv.org/pdf/2606.05868v1
--------------------------------------------------
RETA-LLM: A Retrieval-Augmented Large Language Model Toolkit
https://arxiv.org/pdf/2306.05212v1
--------------------------------------------------
FBI-LLM: Scaling Up Fully Binarized LLMs from Scratch via Autoregressive Distillation
https://arxiv.org/pdf/2407.07093v1
--------------------------------------------------

In [ ]:
embedding_model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

print("Embedding model loaded!")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Embedding model loaded!

In [ ]:
abstracts = df["Abstract"].tolist()

embeddings = embedding_model.encode(
    abstracts,
    show_progress_bar=True
)

print("Embedding Shape:", embeddings.shape)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Embedding Shape: (20, 384)

In [ ]:
dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(
    np.array(embeddings).astype("float32")
)

print("Indexed Papers:", index.ntotal)

Indexed Papers: 20

In [ ]:
faiss.write_index(
    index,
    "research_papers.index"
)

print("FAISS index saved!")

FAISS index saved!

In [ ]:
query = input("Ask a research question: ")

print("Question:", query)

Ask a research question: what are the best method for llm
Question: what are the best method for llm

In [ ]:
query_embedding = embedding_model.encode(
    [query]
)

print(query_embedding.shape)

(1, 384)

In [ ]:
k = 5

distances, indices = index.search(
    np.array(query_embedding).astype("float32"),
    k
)

print(indices)

[[ 9 15 16  2  8]]

In [ ]:
for idx in indices[0]:

    print("=" * 80)

    print("TITLE:")
    print(df.iloc[idx]["Title"])

    print()

    print("ABSTRACT:")
    print(df.iloc[idx]["Abstract"][:700])

    print("\n")

================================================================================
TITLE:
A Survey of LLM $\times$ DATA

ABSTRACT:
The integration of large language model (LLM) and data management (DATA) is rapidly redefining both domains. In this survey, we comprehensively review the bidirectional relationships. On the one hand, DATA4LLM, spanning large-scale data processing, storage, and serving, feeds LLMs with high quality, diversity, and timeliness of data required for stages like pre-training, post-training, retrieval-augmented generation, and agentic workflows: (i) Data processing for LLMs includes scalable acquisition, deduplication, filtering, selection, domain mixing, and synthetic augmentation; (ii) Data Storage for LLMs focuses on efficient data and model formats, distributed and heterogeneous storage hierar


================================================================================
TITLE:
Harnessing Multiple Large Language Models: A Survey on LLM Ensemble

ABSTRACT:
LLM Ensemble -- which involves the comprehensive use of multiple large language models (LLMs), each aimed at handling user queries during downstream inference, to benefit from their individual strengths -- has gained substantial attention recently. The widespread availability of LLMs, coupled with their varying strengths and out-of-the-box usability, has profoundly advanced the field of LLM Ensemble. This paper presents the first systematic review of recent developments in LLM Ensemble. First, we introduce our taxonomy of LLM Ensemble and discuss several related research problems. Then, we provide a more in-depth classification of the methods under the broad categories of "ensemble-before-in


================================================================================
TITLE:
Doing What They Say, Not What They Reason: Locating the Faithfulness Gap in LLM Agents

ABSTRACT:
Do LLM agents act on the reasoning they state? This question of process fidelity is central to using LLMs in social simulation, yet it is hard to measure where no reference for correct behavior exists. We study it in acontrolled setting, a Texas Poker simulator with a verifiable reference action for every decision by decomposing the faithfulness gap into two steps: reasoning-conclusion and conclusion-action. The two steps behave oppositely.


================================================================================
TITLE:
FBI-LLM: Scaling Up Fully Binarized LLMs from Scratch via Autoregressive Distillation

ABSTRACT:
This work presents a Fully BInarized Large Language Model (FBI-LLM), demonstrating for the first time how to train a large-scale binary language model from scratch (not the partial binary or ternary LLM like BitNet b1.58) to match the performance of its full-precision counterparts (e.g., FP16 or BF16) in transformer-based LLMs. It achieves this by employing an autoregressive distillation (AD) loss with maintaining equivalent model dimensions (130M, 1.3B, 7B) and training data volume as regular LLM pretraining, while delivering competitive results in terms of perplexity and task-specific effectiveness. Intriguingly, by analyzing the training trajectory, we find that the pretrained weight is n


================================================================================
TITLE:
Small LLMs Are Weak Tool Learners: A Multi-LLM Agent

ABSTRACT:
Large Language Model (LLM) agents significantly extend the capabilities of standalone LLMs, empowering them to interact with external tools (e.g., APIs, functions) and complete various tasks in a self-directed fashion. The challenge of tool use demands that LLMs not only understand user queries and generate answers accurately but also excel in task planning, tool invocation, and result summarization. While traditional works focus on training a single LLM with all these capabilities, performance limitations become apparent, particularly with smaller models. To overcome these challenges, we propose a novel approach that decomposes the aforementioned capabilities into a planner, caller, and sum

In [ ]:
retrieved_papers = df.iloc[indices[0]]

retrieved_papers

,Title,Authors,Published,Abstract,PDF_URL
9,A Survey of LLM $\times$ DATA,"Xuanhe Zhou, Junxuan He, Wei Zhou, Haodong Che...",2025-05-24,The integration of large language model (LLM) ...,https://arxiv.org/pdf/2505.18458v3
15,Harnessing Multiple Large Language Models: A S...,"Zhijun Chen, Xiaodong Lu, Jingzheng Li, Pengpe...",2025-02-25,LLM Ensemble -- which involves the comprehensi...,https://arxiv.org/pdf/2502.18036v6
16,"Doing What They Say, Not What They Reason: Loc...",Yufeng Wang,2026-05-30,Do LLM agents act on the reasoning they state?...,https://arxiv.org/pdf/2606.00476v1
2,FBI-LLM: Scaling Up Fully Binarized LLMs from ...,"Liqun Ma, Mingjie Sun, Zhiqiang Shen",2024-07-09,This work presents a Fully BInarized Large Lan...,https://arxiv.org/pdf/2407.07093v1
8,Small LLMs Are Weak Tool Learners: A Multi-LLM...,"Weizhou Shen, Chenliang Li, Hongzhan Chen, Min...",2024-01-14,Large Language Model (LLM) agents significantl...,https://arxiv.org/pdf/2401.07324v3

In [ ]:
context = ""

for idx in indices[0]:

    context += df.iloc[idx]["Title"] + "\n"

    context += df.iloc[idx]["Abstract"] + "\n\n"

print(context[:3000])

A Survey of LLM $\times$ DATA
The integration of large language model (LLM) and data management (DATA) is rapidly redefining both domains. In this survey, we comprehensively review the bidirectional relationships. On the one hand, DATA4LLM, spanning large-scale data processing, storage, and serving, feeds LLMs with high quality, diversity, and timeliness of data required for stages like pre-training, post-training, retrieval-augmented generation, and agentic workflows: (i) Data processing for LLMs includes scalable acquisition, deduplication, filtering, selection, domain mixing, and synthetic augmentation; (ii) Data Storage for LLMs focuses on efficient data and model formats, distributed and heterogeneous storage hierarchies, KV-cache management, and fault-tolerant checkpointing; (iii) Data serving for LLMs tackles challenges in RAG (e.g., knowledge post-processing), LLM inference (e.g., prompt compression, data provenance), and training strategies (e.g., data packing and shuffling). On the other hand, in LLM4DATA, LLMs are emerging as general-purpose engines for data management. We review recent advances in (i) data manipulation, including automatic data cleaning, integration, discovery; (ii) data analysis, covering reasoning over structured, semi-structured, and unstructured data, and (iii) system optimization (e.g., configuration tuning, query rewriting, anomaly diagnosis), powered by LLM techniques like retrieval-augmented prompting, task-specialized fine-tuning, and multi-agent collaboration.

Harnessing Multiple Large Language Models: A Survey on LLM Ensemble
LLM Ensemble -- which involves the comprehensive use of multiple large language models (LLMs), each aimed at handling user queries during downstream inference, to benefit from their individual strengths -- has gained substantial attention recently. The widespread availability of LLMs, coupled with their varying strengths and out-of-the-box usability, has profoundly advanced the field of LLM Ensemble. This paper presents the first systematic review of recent developments in LLM Ensemble. First, we introduce our taxonomy of LLM Ensemble and discuss several related research problems. Then, we provide a more in-depth classification of the methods under the broad categories of "ensemble-before-inference, ensemble-during-inference, ensemble-after-inference'', and review all relevant methods. Finally, we introduce related benchmarks and applications, summarize existing studies, and suggest several future research directions. A curated list of papers on LLM Ensemble is available at https://github.com/junchenzhi/Awesome-LLM-Ensemble.

Doing What They Say, Not What They Reason: Locating the Faithfulness Gap in LLM Agents
Do LLM agents act on the reasoning they state? This question of process fidelity is central to using LLMs in social simulation, yet it is hard to measure where no reference for correct behavior exists. We study it in acontrolled setting, a Texas Poker simulator with a verifiabl

In [ ]:
context = ""

for idx in indices[0]:

    context += f"Title: {df.iloc[idx]['Title']}\n"

    context += f"Abstract: {df.iloc[idx]['Abstract']}\n\n"

print(context[:2000])

Title: A Survey of LLM $\times$ DATA
Abstract: The integration of large language model (LLM) and data management (DATA) is rapidly redefining both domains. In this survey, we comprehensively review the bidirectional relationships. On the one hand, DATA4LLM, spanning large-scale data processing, storage, and serving, feeds LLMs with high quality, diversity, and timeliness of data required for stages like pre-training, post-training, retrieval-augmented generation, and agentic workflows: (i) Data processing for LLMs includes scalable acquisition, deduplication, filtering, selection, domain mixing, and synthetic augmentation; (ii) Data Storage for LLMs focuses on efficient data and model formats, distributed and heterogeneous storage hierarchies, KV-cache management, and fault-tolerant checkpointing; (iii) Data serving for LLMs tackles challenges in RAG (e.g., knowledge post-processing), LLM inference (e.g., prompt compression, data provenance), and training strategies (e.g., data packing and shuffling). On the other hand, in LLM4DATA, LLMs are emerging as general-purpose engines for data management. We review recent advances in (i) data manipulation, including automatic data cleaning, integration, discovery; (ii) data analysis, covering reasoning over structured, semi-structured, and unstructured data, and (iii) system optimization (e.g., configuration tuning, query rewriting, anomaly diagnosis), powered by LLM techniques like retrieval-augmented prompting, task-specialized fine-tuning, and multi-agent collaboration.

Title: Harnessing Multiple Large Language Models: A Survey on LLM Ensemble
Abstract: LLM Ensemble -- which involves the comprehensive use of multiple large language models (LLMs), each aimed at handling user queries during downstream inference, to benefit from their individual strengths -- has gained substantial attention recently. The widespread availability of LLMs, coupled with their varying strengths and out-of-the-box usability, has profoundly advan

In [ ]:
!pip install -q transformers

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

In [ ]:
model_name = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

print("LLM Loaded!")

Loading weights:   0%|          | 0/282 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

LLM Loaded!

In [ ]:
prompt = f"""
Based on the research paper abstracts below, write a concise literature review.

{context}

Literature Review:
"""

In [ ]:
context = ""

for idx in indices[0]:

    context += "Title: " + df.iloc[idx]["Title"] + "\n"

    context += df.iloc[idx]["Abstract"][:300] + "\n\n"

In [ ]:
inputs = tokenizer(
    prompt,
    return_tensors="pt",
    truncation=True,
    max_length=512
)

outputs = model.generate(
    **inputs,
    max_new_tokens=200,
    do_sample=False
)

review = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print(review)

The LLM Ensemble approach is a new approach to large language models, and it is a major step forward in the field of large language models.

In [ ]:
print("Sources Used:\n")

for idx in indices[0]:

    print("-" * 80)

    print(df.iloc[idx]["Title"])

    print(df.iloc[idx]["PDF_URL"])

Sources Used:

--------------------------------------------------------------------------------
A Survey of LLM $\times$ DATA
https://arxiv.org/pdf/2505.18458v3
--------------------------------------------------------------------------------
Harnessing Multiple Large Language Models: A Survey on LLM Ensemble
https://arxiv.org/pdf/2502.18036v6
--------------------------------------------------------------------------------
Doing What They Say, Not What They Reason: Locating the Faithfulness Gap in LLM Agents
https://arxiv.org/pdf/2606.00476v1
--------------------------------------------------------------------------------
FBI-LLM: Scaling Up Fully Binarized LLMs from Scratch via Autoregressive Distillation
https://arxiv.org/pdf/2407.07093v1
--------------------------------------------------------------------------------
Small LLMs Are Weak Tool Learners: A Multi-LLM Agent
https://arxiv.org/pdf/2401.07324v3

In [ ]:
results = {
    "Question": query,
    "Generated_Answer": review
}

print(results)

{'Question': 'what are the best method for llm', 'Generated_Answer': 'The LLM Ensemble approach is a new approach to large language models, and it is a major step forward in the field of large language models.'}

In [ ]:
prompt = f"""
Write a literature review based on these research papers.

Discuss:

1. Main research themes
2. Common methods
3. Current challenges
4. Future directions

Research Papers:

{context}

Literature Review:
"""

In [ ]:
inputs = tokenizer(
    prompt,
    return_tensors="pt",
    truncation=True,
    max_length=512
)

outputs = model.generate(
    **inputs,
    max_new_tokens=300,
    do_sample=False
)

literature_review = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print(literature_review)

This paper argues that LLMs are a useful tool for a wide range of tasks, including a self-directed learning style. It also argues that LLMs are not only useful for a wide range of tasks, but also for a wide range of tasks.

In [ ]:
prompt = f"""
Based on these research papers:

{context}

Identify:

1. Common research directions
2. Limitations of existing work
3. Potential research gaps
4. Future research opportunities

Research Gap Analysis:
"""

In [ ]:
inputs = tokenizer(
    prompt,
    return_tensors="pt",
    truncation=True,
    max_length=512
)

outputs = model.generate(
    **inputs,
    max_new_tokens=300,
    do_sample=False
)

research_gap = tokenizer.decode(
    outputs[0],
    skip_special_tokens=True
)

print(research_gap)

Large Language Models Are Weak Tool Learners: A Multi-LLM Agent

In [ ]:
all_text = ""

for i in range(len(df)):

    all_text += df.iloc[i]["Title"] + " "

    all_text += df.iloc[i]["Abstract"] + " "

print("Text collected!")

Text collected!

In [ ]:
!pip install -q nltk

In [ ]:
import nltk

from nltk.corpus import stopwords

from collections import Counter

In [ ]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
stop_words = set(stopwords.words("english"))

words = all_text.lower().split()

clean_words = []

for word in words:

    word = word.strip(".,()[]{}:;!?\"'")

    if len(word) > 3 and word not in stop_words:

        clean_words.append(word)

print("Words cleaned!")

Words cleaned!

In [ ]:
word_counts = Counter(clean_words)

top_words = word_counts.most_common(20)

top_words

[('llms', 69),
 ('language', 22),
 ('models', 22),
 ('large', 21),
 ('data', 21),
 ('knowledge', 16),
 ('inference', 15),
 ('model', 14),
 ('tasks', 13),
 ('training', 12),
 ('across', 12),
 ('framework', 11),
 ('systems', 11),
 ('llm-as-a-judge', 11),
 ('performance', 10),
 ('diverse', 10),
 ('however', 9),
 ('serving', 9),
 ('approach', 8),
 ('capabilities', 8)]

In [ ]:
print("Top Research Trends\n")

for word, count in top_words:

    print(f"{word}: {count}")

Top Research Trends

llms: 69
language: 22
models: 22
large: 21
data: 21
knowledge: 16
inference: 15
model: 14
tasks: 13
training: 12
across: 12
framework: 11
systems: 11
llm-as-a-judge: 11
performance: 10
diverse: 10
however: 9
serving: 9
approach: 8
capabilities: 8

In [ ]:
research_phrases = [

    "large language model",

    "retrieval augmented generation",

    "rag",

    "llm ensemble",

    "agent",

    "multi agent",

    "reasoning",

    "fine tuning",

    "knowledge graph",

    "hallucination",

    "benchmark",

    "inference",

    "alignment",

    "tool learning",

    "prompt engineering",

    "recommendation system",

    "graph neural network"
]

In [ ]:
phrase_counts = {}

text = all_text.lower()

for phrase in research_phrases:

    phrase_counts[phrase] = text.count(
        phrase.lower()
    )

In [ ]:
sorted_trends = sorted(
    phrase_counts.items(),
    key=lambda x: x[1],
    reverse=True
)

In [ ]:
print("Research Trend Analysis\n")

for phrase, count in sorted_trends:

    if count > 0:

        print(
            f"{phrase}: {count}"
        )

Research Trend Analysis

large language model: 20
inference: 18
rag: 13
agent: 12
alignment: 8
benchmark: 7
llm ensemble: 6
reasoning: 5
knowledge graph: 3
hallucination: 3
tool learning: 1

In [ ]:
report = ""

report += "=" * 60 + "\n"
report += "RESEARCH PAPER ASSISTANT REPORT\n"
report += "=" * 60 + "\n\n"

report += f"Research Topic: {TOPIC}\n\n"

report += f"Number of Papers Retrieved: {len(df)}\n\n"

In [ ]:
report += "TOP RESEARCH TRENDS\n"
report += "-" * 30 + "\n"

for phrase, count in sorted_trends:

    if count > 0:

        report += f"{phrase}: {count}\n"

report += "\n"

In [ ]:
report += "TOP RELEVANT PAPERS\n"
report += "-" * 30 + "\n"

for idx in indices[0]:

    report += (
        df.iloc[idx]["Title"] + "\n"
    )

report += "\n"

In [ ]:
report += "LITERATURE REVIEW\n"
report += "-" * 30 + "\n"

report += literature_review

report += "\n\n"

In [ ]:
report += "QUESTION ANSWERING\n"
report += "-" * 30 + "\n"

report += f"Question: {query}\n\n"

report += f"Answer: {review}\n\n"

In [ ]:
print(report[:5000])

============================================================
RESEARCH PAPER ASSISTANT REPORT
============================================================

Research Topic: llm

Number of Papers Retrieved: 20

TOP RESEARCH TRENDS
------------------------------
large language model: 20
inference: 18
rag: 13
agent: 12
alignment: 8
benchmark: 7
llm ensemble: 6
reasoning: 5
knowledge graph: 3
hallucination: 3
tool learning: 1

TOP RELEVANT PAPERS
------------------------------
A Survey of LLM $\times$ DATA
Harnessing Multiple Large Language Models: A Survey on LLM Ensemble
Doing What They Say, Not What They Reason: Locating the Faithfulness Gap in LLM Agents
FBI-LLM: Scaling Up Fully Binarized LLMs from Scratch via Autoregressive Distillation
Small LLMs Are Weak Tool Learners: A Multi-LLM Agent

LITERATURE REVIEW
------------------------------
This paper argues that LLMs are a useful tool for a wide range of tasks, including a self-directed learning style. It also argues that LLMs are not only useful for a wide range of tasks, but also for a wide range of tasks.

QUESTION ANSWERING
------------------------------
Question: what are the best method for llm

Answer: The LLM Ensemble approach is a new approach to large language models, and it is a major step forward in the field of large language models.

In [ ]:
with open(
    "research_report.txt",
    "w",
    encoding="utf-8"
) as f:

    f.write(report)

print(
    "Report saved successfully!"
)

Report saved successfully!

In [ ]:
from google.colab import files

files.download(
    "research_report.txt"
)